### ISSUE TITLE
Add Table of Contents

### ISSUE THREAD

**Issue by pmuens** [photonlines/Intuitive-Overview-of-Linear-Algebra-Fundamentals#1]
This is a really great resource! Thank you very much for putting this together.

While skimming through this I was hoping for Matrix Calculus and I wasn't disappointed 👌. It would be nice to have a TOC to see at a glance what's in here.

**Comment by photonlines** [comment]
Thanks for the kind words Philipp - much appreciated!

I've added a table of contents just now so hopefully it helps out. If you
have any other suggestions or great resources on linear algebra you want to
share, please let me know!

All the best,

Nick
